name: Paisewali
favicon: null
layout_spectrum: 0.4720072355121374
typography_spectrum: 0.9142680545337498
title: Paisewali
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-51199805-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.375
  lightness: 0.5732341669499874
  saturation: 0.6928756257984787
  rhythmicContrast: 0.9933245298452675
purpose: []
